---
title: "ggsom"
author: "Felipe Carvalho"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{ggsom}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## ggsom 

Set of different visualizations for the kohonen SOMs (Self-Organising Maps) package using ggplot.


## Example of line plot with color
```{r, fig.height=8, fig.width=7, fig.align='center'}
library(ggsom)
suppressMessages(library(tidyverse))
suppressMessages(library(kohonen))
library(ggthemes)

iris_som <-
kohonen::som(scale(iris[1:4]), grid = somgrid(6, 4, "rectangular"))
ggsom::ggsom_line(aes_som(iris_som), TRUE)
```

## Example of line plot without color
```{r, fig.height=8, fig.width=7, fig.align='center'}
library(ggsom)
suppressMessages(library(tidyverse))
suppressMessages(library(kohonen))
library(ggthemes)

iris_som <-
kohonen::som(scale(iris[1:4]), grid = somgrid(6, 4, "rectangular"))
ggsom::ggsom_line(aes_som(iris_som), FALSE)
```
  
## Example of ribbon plot

```{r, fig.height=8, fig.width=7, fig.align='center'}
library(ggsom)
suppressMessages(library(tidyverse))
suppressMessages(library(kohonen))
library(ggthemes)

iris_som <-
kohonen::som(scale(iris[1:4]), grid = somgrid(6, 4, "rectangular"))
ggsom_ribbon(aes_som(iris_som, cutree_value = 2) , TRUE)
```

## Example of rect plot

```{r, fig.height=8, fig.width=7, fig.align='center'}
library(ggsom)
suppressMessages(library(tidyverse))
suppressMessages(library(kohonen))
library(ggthemes)

iris_som <-
kohonen::som(scale(iris[1:4]), grid = somgrid(6, 4, "rectangular"))
ggsom_rect(aes_som(iris_som, cutree_value = 4), TRUE)
```
  
